### ISSUE TITLE
No Refresh Token Found

### ISSUE THREAD

**Issue by fanul-expose** [jonathanTIE/googledrive-copy-downloader#11]
when i use credentials to auth... it always throw :

`###############
Traceback (most recent call last):
  File "/Users/bpjstk/Documents/script/python/Gdrive_copy/gDriveCopyDownloader.py", line 52, in <module>
    drive = GoogleAuthManager.create_drive_manager()
  File "/Users/bpjstk/Documents/script/python/Gdrive_copy/GoogleAuthManager.py", line 18, in create_drive_manager
    authorize_from_credential(gAuth, bool)
  File "/Users/bpjstk/Documents/script/python/Gdrive_copy/GoogleAuthManager.py", line 32, in authorize_from_credential
    gAuth.Refresh()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pydrive/auth.py", line 470, in Refresh
    raise RefreshError('No refresh_token found.'
pydrive.auth.RefreshError: No refresh_token found.Please set access_type of OAuth to offline.`

can someone point mo how to fix it.. because i'd like to run this script in automated environment on my dietpi...

**Comment by fanul-expose** [comment]
got it solved changed auth process in GoogleAuthManager.py in line 32 with this:

`        #gAuth.Refresh()
        try:
            gAuth.Refresh()
        except:
            gAuth.CommandLineAuth()`
