### ISSUE TITLE
Folder ID Change?

### ISSUE THREAD

**Issue by Orochi101** [jonathanTIE/googledrive-copy-downloader#8]
Hi, I just started using this script and it's been awesome lately but I'm having an issue with larger files. For example, let's say the file I want to download is larger than the space left in my drive storage, I get an error saying the file has exceeded user storage. I have a regular email with no subscriptions for extra storage BUT I have a team drive with unlimited storage. Would it be possible to shift or change the folder ID of temp folder to the team drive rather than my user storage? That should solve my problem for larger files.

**Comment by jonathanTIE** [comment]
Hello, yes you should be able to do that : 
[https://stackoverflow.com/questions/55729923/how-can-i-access-a-team-drive-instead-of-personal-google-drive-using-pydrive](url)
What you need to do is to change the query, at line 19 of gDrivelibrary.py (But I can't try it at the moment) : 

>     query = "title='Temp folder for script' and mimeType='application/vnd.google-apps.folder'" \
>           " and '<Team_Drive_Id_Or_Folder_Id>' in parents and trashed=false"

**Comment by Orochi101** [comment]
> 
> 
> Hello, yes you should be able to do that :
> [https://stackoverflow.com/questions/55729923/how-can-i-access-a-team-drive-instead-of-personal-google-drive-using-pydrive](url)
> What you need to do is to change the query, at line 19 of gDrivelibrary.py (But I can't try it at the moment) :
> 
> > ```
> > query = "title='Temp folder for script' and mimeType='application/vnd.google-apps.folder'" \
> >       " and '<Team_Drive_Id_Or_Folder_Id>' in parents and trashed=false"
> > ```

Thank you for replying!
I just tried your suggestion and I get this list of error

"Traceback (most recent call last):
  File "gDriveCopyDownloader.py", line 58, in <module>
    copiedFile = gDriveLibrary.copy_file(drive, fileID)
  File "C:\Users\User\Downloads\rclone-v1.51.0-windows-amd64\GDriveCPDownloader\gDriveLibrary.py", line 64, in copy_file
    folderID = get_Gdrive_folder_id(drive, drive.auth.service, "Temp folder for script")
  File "C:\Users\User\Downloads\rclone-v1.51.0-windows-amd64\GDriveCPDownloader\gDriveLibrary.py", line 22, in get_Gdrive_folder_id
    for subList in listFolders:
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\pydrive\apiattr.py", line 146, in __next__
    result = self._GetList()
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\pydrive\auth.py", line 75, in _decorated
    return decoratee(self, *args, **kwargs)
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\pydrive\files.py", line 63, in _GetList
    self.metadata = self.auth.service.files().list(**dict(self)).execute(
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/drive/v2/files?q=title%3D%27Temp+folder+for+script%27+and+mimeType%3D%27application%2Fvnd.google-apps.folder%27+and+%27%3C0AOU-OtTMsFLIUk9PVA%3E%27+in+parents+and+trashed%3Dtrue&alt=json returned "File not found:">"

**Comment by Orochi101** [comment]
Deleted my previous comment because I forgot I set trashed to true since I don't have to worry about space anymore. But now I set it back to false and I'm still having the same issue.


> Traceback (most recent call last):
>   File "gDriveCopyDownloader.py", line 58, in <module>
>     copiedFile = gDriveLibrary.copy_file(drive, fileID)
>   File "C:\Users\User\Downloads\rclone-v1.51.0-windows-amd64\GDriveCPDownloader\gDriveLibrary.py", line 64, in copy_file
>     folderID = get_Gdrive_folder_id(drive, drive.auth.service, "Temp folder for script")
>   File "C:\Users\User\Downloads\rclone-v1.51.0-windows-amd64\GDriveCPDownloader\gDriveLibrary.py", line 22, in get_Gdrive_folder_id
>     for subList in listFolders:
>   File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\pydrive\apiattr.py", line 146, in __next__
>     result = self._GetList()
>   File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\pydrive\auth.py", line 75, in _decorated
>     return decoratee(self, *args, **kwargs)
>   File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\pydrive\files.py", line 63, in _GetList
>     self.metadata = self.auth.service.files().list(**dict(self)).execute(
>   File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
>     return wrapped(*args, **kwargs)
>   File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\googleapiclient\http.py", line 856, in execute
>     raise HttpError(resp, content, uri=self.uri)
> googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/drive/v2/files?q=title%3D%27Temp+folder+for+script%27+and+mimeType%3D%27application%2Fvnd.google-apps.folder%27+and+%27%3C"Team-Drive-ID"%3E%27+in+parents+and+trashed%3Dfalse&alt=json returned "File not found:">

**Comment by jonathanTIE** [comment]
You don't need to "quote" it with the <> characters, remove them between the quotes like : 
> '0AOU-OtTMsFLIUk9PVA' in parents

**Comment by Orochi101** [comment]
Alright, I've updated my comment.
Thanks for looking into it
